src/FBTest/FBTest.jsx

cannot test on the most updated code of itaigi

Issue #34 solved: FB.api(/postID?fields=source)

---

index.html
src/App/App.css
src/GuanKiann/ToLam/ToLam.jsx
src/GuanKiann/Tshue/Tshue.jsx

Remove left padding of menu and add icon

---

index.html
src/App/App.css
src/App/App.jsx
src/GuanKiann/ToLam/ToLam.css
src/GuanKiann/ToLam/ToLam.jsx

icon menu bar

---

server-side/requirements.txt
src/GuanKiann/ABo/ABo.jsx

加免登入送建議的前端

---

src/App/App.jsx
src/GuanKiann/ABo/ABo.jsx
src/GuanKiann/ABo/APui.jsx

用react-modal作跳出視窗

---

README.md
server-side/itaigi/__init__.py
server-side/itaigi/celery.py
server-side/itaigi/settings.py
server-side/requirements.txt

使用 celery 達成非同步
broker 先使用 rabbitmq，之後會先做詞條討論會用到 redis ，先分開來之後開發完再都搬去 redis

提供講法 google doc 相關搬去 mq

---

src/GuanKiann/HuatIm/HuatIm.css
src/GuanKiann/HuatIm/HuatIm.jsx
src/GuanKiann/Su/Su.jsx

https://github.com/g0v/itaigi/issues/51
.ogg 換成 .mp3 因為看到 [Safari & IE 不支援](http://www.w3schools.com/html/html5_audio.asp)

#51: .ogg to .mp3, custom play button

---

.gitignore
src/Iah/The/The.jsx

#83 真的很會，所有詞都有台語講法了！

---

src/index.js

網址烏白拍嘛會到首頁

---

README.md

佇readme的後端加說明

---

src/FBTest/FBTest.jsx
src/GuanKiann/Tshue/Tshue.jsx
src/Iah/Kong/Kong.jsx

https://github.com/g0v/itaigi/issues/115

更改搜尋placeholder

---

src/Iah/Iong/Iong.jsx
src/Iah/Iong/config.js

https://github.com/g0v/itaigi/issues/128

setup good tool

---

src/GuanKiann/ABo/ABo.jsx
src/GuanKiann/LokIm/LokIm.jsx

https://github.com/g0v/itaigi/issues/126

issue 126 solved.

---

src/GuanKiann/ABo/ABo.jsx

送出新詞的時陣，按鈕愛鎖起來

---

src/GuanKiann/ABo/ABo.jsx
src/GuanKiann/LokIm/LokIm.jsx

#138 #126 
感謝 imkojima  #143 回報

自import共錄音提掉

---

README.md

更新 README.md，
新增了檢查及更新 node.js 版本的步驟說明

update README.md - check & update node.js version

---

index.html

https://github.com/g0v/itaigi/issues/156
先做全站的，讓現在分享就有好看一點的圖

global meta

---

README.md
src/App/App.jsx

加slack佮fb連結

---

src/Iah/About/About.jsx

#134 
原本較長
這馬三四句一段，較好讀
@liz462 會當請你看一下 <http://giam7.itaigi.tw/about> 有改了無好的所在無

關於本站段落切較短咧

---

src/GuanKiann/LaiLik/LaiLik.jsx

文案改`出處`較好聽

---

src/Iah/Kong/Kong.css
src/Iah/Kong/Kong.jsx

#166
下佇： http://test.itaigi.tw/

固定講法div的闊度

---

src/GuanKiann/ABo/ABo.jsx

有臺羅無漢字嘛會使提供講法

---

src/GuanKiann/Su/TuiIngHuaGi.js

對應華語改用Link，配合react-router的single page

---

package.json

我的筆電
```
rm node_modules/gh-pages/.cache/ -rf
```
-rf 寫在檔名後會跳error
我改成
```
rm -rf node_modules/gh-pages/.cache/
```

調整deploy script rm command option的位置

---

src/App/App.jsx
src/FBTest/FBTest.jsx
src/GuanKiann/分享鍵/分享鍵.jsx
src/Iah/Iong/Iong.css
src/Iah/Iong/Iong.jsx
src/Iah/Kong/無關鍵字.jsx
src/Iah/The/顯示一個問題.jsx
src/Iah/The/顯示選單.jsx

https://github.com/g0v/itaigi/issues/168#issuecomment-236344227

調整「我很會」的disqus對應

---

server-side/requirements.txt

update requirements.txt 's 臺灣言語平臺 version

---

src/Iah/The/The.css
src/Iah/The/The.jsx

加css控制「我很會」闊度

---

src/GuanKiann/HuatIm/HapSing.jsx

進前transmit的函式提無清氣

---

index.html
src/App/App.css
src/GuanKiann/GuaGi/GuaGi.jsx
src/GuanKiann/分享鍵/分享鍵.css
src/Iah/Kong/Kong.css

RWD: Add viewport meta, Kong page adjustment

---

src/GuanKiann/HuatIm/HapSing.jsx

https://g0v-tw.slack.com/archives/itaigi/p1471225571000975 講基本詞莫用合的
所以 #217 莫ti7
先修 #216

有腔口的臺語合成修好

---

server-side/requirements.txt

更新資料庫的版本，需要migrate

---

server-side/requirements.txt

補平臺，予伊配合新資料庫

---

server-side/佳怡表匯入資料庫.py

因為這个xls干焦詞典，無語句問題

---

src/Iah/Kong/其他建議.jsx

相關的詞依序排列，不依華語不同換行

---

src/App/App.jsx
src/App/後端.jsx

後端網址獨立出來，較好開發 

---

src/GuanKiann/HuatIm/HapSing.jsx

另外租一台來合聲音 #219
若無問題，就愛改domain name

合成換新的API，由後端處理標點符號的問題

---

src/Iah/Kong/Kong.css
src/Iah/Kong/無關鍵字.jsx

#285 
jsx 專住在 className 的切換
剩下的交給css管理
但是我跑npm test遇到一些問題，所以文法的部份希望有合規定，至於css的縮排問題...對你們造成困擾我真的很抱歉（在編輯器上沒看出那是tab）
如果deploy到測試機上面沒問題的話，就把他rebase成一個commit後再merge吧

燒燙燙新詞的loading

---

src/FBTest/FBTest.jsx

Fix Facebook expired image link

---

src/Iah/Kong/Kong.css
src/Iah/Kong/無關鍵字.jsx

Fix #287 , my fault for that
also add a little css on it (a tag will act as p tag when its href attribute is blank)

fix "顯示多一點" link and add pointer css on hover

---

src/GuanKiann/ABo/ABo.jsx
src/GuanKiann/GuaGi/GuaGi.jsx
src/GuanKiann/KiuKongHuat/KiuKongHuat.jsx
src/Iah/Kong/Kong.jsx
src/Iah/Kong/有講法.jsx
src/Iah/Kong/無結果.jsx

https://github.com/g0v/itaigi/issues/247#issuecomment-250900222
截圖程式截出來有色差 @@

共啊無徙入去外語內底

---

src/GuanKiann/HuatIm/HapSing.jsx

#263
需要audio/x-wav，毋過w3school預設audio/wav 
試規晡 @@
http://www.w3schools.com/html/html5_audio.asp

修android原生webkit瀏覽器放合成

---

src/GuanKiann/Tshue/Tshue.jsx

拍一字時，莫ajax

---

src/Iah/Kong/Kong.jsx

有詞條就免載入燒燙燙

---

src/GuanKiann/Tshue/Tshue.jsx
src/Iah/Kong/Kong.jsx

揤鈕仔，揣內底的內容用update綴咧改

---

src/App/App.jsx

不用transmit改直接在constructor呼叫

---

src/GuanKiann/Tshue/Tshue.jsx

修undefined

---

src/App/App.jsx
src/GuanKiann/Tshue/Tshue.jsx
src/Iah/Kong/其他建議.jsx

http://test.itaigi.tw/k/%E4%B8%80
載入`一`袂等傷久

預設顯示上濟30个相關建議

---

src/Iah/Kong/無結果.jsx

#342 無講法的區塊補上semantic-ui css

---

src/GuanKiann/KiuKongHuat/SangTshut.jsx

#357 求講法modal，參考修改後的阿肥

---

webpack.config.prod.js

#370 回復產生sourceMap的選項

---

src/GuanKiann/Su/Su.jsx
src/GuanKiann/Su/一个建議.jsx
src/Iah/Kong/Kong.jsx

#372 
補上套件文件提供的語法`shouldContainerUpdate()`

升級transmit之後發現ajax重複呼叫

---

src/GuanKiann/ToLam/ToLam.jsx
src/GuanKiann/TshiuKiSuanTuann/TshiuKiSuanTuann.jsx
src/Iah/Mia/正規化.jsx
src/index.js
src/後端.jsx

加正規化團隊名人堂的前端

---

src/Iah/Iong/Iong.jsx

修samsung grand prime超出頁面的問題 

---

README.md

後端開發移到wiki

---

src/GuanKiann/Su/Su.css
src/GuanKiann/Su/Su.jsx

紀錄使用者的瀏覽器與回報時間
目前只是先把資訊印在console
#391

回報sever 是不是活的

---

.travis.yml

g0v/itaigi#426
cc. @sih4sing5hong5

Added Travis-CI auto deploy gh-pages function

---

src/GuanKiann/HuatIm/HapSing.jsx

為著徙主機，先換domain name

---

src/GuanKiann/HuatIm/HapSing.jsx
src/GuanKiann/HuatIm/HuatIm.jsx
src/GuanKiann/例句/例句鈕仔.jsx

區別選單與例句icon，並增加功能提示

---

src/GuanKiann/GuaGi/GuaGi.css

最大化視窗時card與search bar對齊

---

src/App/App.css
src/GuanKiann/TshiuKiSuanTuann/KuahPau.jsx
src/GuanKiann/Tshue/Tshue.jsx
src/Iah/Kong/Kong.jsx
src/Iah/Kong/無關鍵字.jsx

fix #447 試著將search bar拉近user一點，敬請指導

Mobile thinking

---

src/GuanKiann/Su/Su.jsx
src/GuanKiann/例句/例句表.jsx

Fix #477, #478

---

src/Iah/Iong/config.js

更新好工具辭典區，加一个ChhoeTaigi揣台語
https://chhoe.taigi.info/

好工具ChhoeTaigi

---

src/GuanKiann/HuatIm/HapSing.jsx

合成的api改用台語

---

server-side/Dockerfile

```
cd server-side/
time docker build -t itaigi .
docker run -ti -p 8001:8001 --rm itaigi gunicorn itaigi.wsgi
```

ka gunicorn dockerfile

---

src/Iah/名姓/名姓.jsx

add the theme of the form

---

src/GuanKiann/ABo/ABo.jsx
src/GuanKiann/KiuKongHuat/KiuKongHuat.jsx
src/GuanKiann/Su/Su.jsx

先suà掉X-CSRF看覓

---

package.json
server-side/Dockerfile

django 2.1有session samesite，無domain無法度設定

先退轉django2.0

---

src/GuanKiann/ABo/ABo.jsx
src/GuanKiann/KiuKongHuat/KiuKongHuat.jsx
src/GuanKiann/Su/Su.jsx

Revert "先suà掉X-CSRF看覓"

---

src/GuanKiann/HuatIm/HapSing.jsx

Reverts g0v/itaigi#518
因為換頁需要更新音檔

Revert "莫先load 音檔，減少server 負擔"

---

src/Iah/Kong/其他建議.jsx

其他建議顯示較少--leh

---

src/Iah/Iong/config.js

新增PhahTaigi 台語輸入法iOS版連結

---

server-side/Dockerfile
server-side/itaigi/settings.py

https://github.com/i3thuan5/tai5-uan5_gian5-gi2_phing5-tai5/pull/215

限制「無建議的外語」數量

---

src/Iah/The/選單項目.jsx

https://github.com/i3thuan5/tai5-uan5_gian5-gi2_phing5-tai5/pull/216

配合後端，無建議的外語，直接提華語內容ê list就好

---

src/後端.jsx

https://github.com/g0v/itaigi-mia-senn/pull/7

配合itaigi ê domain。

---

src/Iah/Iong/config.js

Fix hyperlink for 臺灣閩南語推薦用字700字詞

[BUGFIX] fix hyperlink for 臺灣閩南語推薦用字700字詞
